ALTER TABLE users
ADD COLUMN avatar VARCHAR(255) NULL AFTER role,
ADD COLUMN is_logged_in TINYINT(1) DEFAULT 0,
ADD COLUMN last_login_at DATETIME NULL,
ADD COLUMN last_logout_at DATETIME NULL,
ADD COLUMN created_by INT NULL,
ADD COLUMN updated_by INT NULL,
ADD COLUMN deleted_by INT NULL,
ADD COLUMN deleted_at DATETIME NULL,
ADD COLUMN emp_codigo INT NOT NULL AFTER id,
ADD COLUMN phone VARCHAR(50) NULL AFTER email,
ADD COLUMN address VARCHAR(255) NULL AFTER phone,
ADD COLUMN status ENUM('activo', 'inactivo') NOT NULL DEFAULT 'activo' AFTER address,
MODIFY COLUMN deleted_at DATETIME NULL;