ALTER TABLE users
ADD COLUMN avatar VARCHAR(255) NULL AFTER role,
ADD COLUMN is_logged_in TINYINT(1) DEFAULT 0,
ADD COLUMN last_login_at DATETIME NULL,
ADD COLUMN last_logout_at DATETIME NULL,
ADD COLUMN created_by INT NULL,
ADD COLUMN updated_by INT NULL,
ADD COLUMN deleted_by INT NULL,
ADD COLUMN deleted_at DATETIME NULL,
ADD COLUMN company_id INT NOT NULL AFTER id;